version: 2

artifacts:
  - name: planning
    build:
      type: custom
      runtime:
        type: standard1/arm64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
          import_path: src
      base_container_image:
        from: ghcr.io/oguzkaganozt/autoware-openadk:planning-demo-before-ota-aarch64
      phases:
        - name: init
          exec: "true"
      output_container_image:
        from: init

simulations:
  - name: planning_sim
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: planning
      runtime:
        type: standard1/arm64/medium
        workdir: /autoware
      parameters:
        launch_autoware: "true"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe
        vehicle_model: sample_vehicle
        sensor_model: sample_sensor_kit
        initialize_duration: "45"
