- name: Install cuDNN and TensorRT
  become: true
  ansible.builtin.apt:
    name:
      - libcudnn8={{ cudnn_version }}
      - libnvinfer8={{ tensorrt_version }}
      - libnvinfer-plugin8={{ tensorrt_version }}
      - libnvparsers8={{ tensorrt_version }}
      - libnvonnxparsers8={{ tensorrt_version }}
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true

- name: Install cuDNN and TensorRT Dev
  become: true
  ansible.builtin.apt:
    name:
      - libcudnn8-dev={{ cudnn_version }}
      - libnvinfer-dev={{ tensorrt_version }}
      - libnvinfer-plugin-dev={{ tensorrt_version }}
      - libnvparsers-dev={{ tensorrt_version }}
      - libnvonnxparsers-dev={{ tensorrt_version }}
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true
  when: install_devel | bool

# apt-mark hold
- name: Prevent CUDA-related packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - libcudnn8
    - libnvinfer8
    - libnvinfer-plugin8
    - libnvparsers8
    - libnvonnxparsers8

- name: Prevent CUDA-related Dev packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - libcudnn8-dev
    - libnvinfer-dev
    - libnvinfer-plugin-dev
    - libnvparsers-dev
    - libnvonnxparsers-dev
  when: install_devel | bool

- name: Software properties common - RViz2 black screen fix
  become: true
  ansible.builtin.apt:
    name:
    - software-properties-common
    update_cache: true

- name: Add kisak-mesa repository - RViz2 black screen fix
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:kisak/kisak-mesa
    state: present

- name: Install mesa libraries - RViz2 black screen fix
  become: true
  ansible.builtin.apt:
    name:
    - libegl-mesa0
    - libegl1-mesa-dev
    - libgbm-dev
    - libgbm1
    - libgl1-mesa-dev
    - libgl1-mesa-dri
    - libglapi-mesa
    - libglx-mesa0
    update_cache: true
  
- name: Ensure directory exists - Vulkan
  file:
    path: /etc/vulkan/icd.d
    state: directory
    mode: '0755'

- name: Register Vulkan GPU Vendor
  get_url:
    url: https://gitlab.com/nvidia/container-images/vulkan/raw/dc389b0445c788901fda1d85be96fd1cb9410164/nvidia_icd.json
    dest: /etc/vulkan/icd.d/nvidia_icd.json
    mode: '0644'

- name: Ensure directory exists- OpenGL
  file:
    path: /etc/glvnd/egl_vendor.d
    state: directory
    mode: '0755'

- name: Register OpenGL GPU Vendor
  get_url:
    url: https://gitlab.com/nvidia/container-images/opengl/raw/5191cf205d3e4bb1150091f9464499b076104354/glvnd/runtime/10_nvidia.json
    dest: /etc/glvnd/egl_vendor.d/10_nvidia.json
    mode: '0644'
  
- name: Ensure OpenCL vendors directory exists
  file:
    path: /etc/OpenCL/vendors
    state: directory
    mode: '0755'

- name: Create /etc/OpenCL/vendors/nvidia.icd
  copy: 
    content: "libnvidia-opencl.so.1"
    dest: /etc/OpenCL/vendors/nvidia.icd
    mode: '0644'
