- hosts: localhost
  connection: local
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 is supported for this branch. Please refer to https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/.
      when: ansible_distribution_version != '22.04'

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
          - gdown
  roles:
    # Autoware Universe base dependencies
    - role: autoware.dev_env.base.ros2
    - role: autoware.dev_env.base.rmw_implementation
    - role: autoware.dev_env.base.gdown
