- hosts: localhost
  connection: local
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 is supported for this branch. Please refer to https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/.
      when: ansible_distribution_version != '22.04'

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"

  roles:
    # Development environment dependencies
    - role: autoware.dev_env.devel.ccache
    - role: autoware.dev_env.devel.plotjuggler
    - role: autoware.dev_env.devel.pre_commit
    - role: autoware.dev_env.devel.ros2_dev_tools
